name: C++ CI - MSVC Build

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest  # Use the latest Windows runner with MSVC pre-installed

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up MSVC using the setup-msbuild action
    - name: Set up Visual Studio (MSVC)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build tests
      shell: cmd
      run: |
        REM Compile main.cpp in TEST MODE (RUN_TESTS defined)
        REM /EHsc = standar C++ exception handling
        REM /std:c++17 standard

        cl /nologo /EHsc /std:c++17 /D RUN_TESTS main.cpp /FE:tests.exe

    - name: Run tests
      shell: cmd
      run: |
        tests.exe
